spring:
  application:
    name: mundial26

  datasource:
    url: jdbc:mariadb://localhost:3306/mundial26
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  output:
    ansi:
      enabled: always
server:
  port: 8080

logging:
  level:
    com.mundial2026: DEBUG
    org.springframework.web: DEBUG
